name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        container:
          - ghcr.io/c-cube/c-cube-commmon/ci-4.14:latest
          - ghcr.io/c-cube/c-cube-commmon/ci-5.1:latest
          - ghcr.io/c-cube/c-cube-commmon/ci-5.4:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6

      - run: apt update && opam install ./tiny_httpd.opam ./tiny_httpd_camlzip.opam --deps-only --with-test
      - run: opam exec -- dune build @install -p tiny_httpd,tiny_httpd_camlzip

      - name: Build tiny_httpd_eio (OCaml 5.x only)
        if: ${{ !contains(matrix.container, 'ci-4.') }}
        run: |
          opam install ./tiny_httpd_eio.opam --deps-only --with-test
          opam exec -- dune build @install -p tiny_httpd,tiny_httpd_camlzip,tiny_httpd_eio

      - run: opam exec -- dune build @src/runtest @examples/runtest @tests/runtest -p tiny_httpd

      - run: opam install tiny_httpd

      - run: opam exec -- dune build @src/runtest @examples/runtest @tests/runtest -p tiny_httpd_camlzip

      - run: opam install logs magic-mime -y

      - name: Final build (OCaml 4.x)
        if: ${{ contains(matrix.container, 'ci-4.') }}
        run: opam exec -- dune build @install -p tiny_httpd,tiny_httpd_camlzip

      - name: Final build (OCaml 5.x)
        if: ${{ !contains(matrix.container, 'ci-4.') }}
        run: opam exec -- dune build @install -p tiny_httpd,tiny_httpd_camlzip,tiny_httpd_eio
